import os
import datetime
from typing import Optional, Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "reports")

def generate_legal_report(media_id: str, detection_data: Dict[str, Any], heatmap_path: Optional[str] = None) -> Optional[str]:
    """
    Generate a PDF legal evidence report for a given media detection.
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)
    out_path = os.path.join(REPORTS_DIR, f"Legal_Evidence_Report_{media_id}.pdf")

    try:
        doc = SimpleDocTemplate(out_path, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []

        # Title
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=20,
            textColor=colors.HexColor("#1A365D"),
            alignment=1 # Center
        )
        elements.append(Paragraph("MediaShield AI - Legal Evidence Report", title_style))
        elements.append(Spacer(1, 12))

        # Metadata Section
        elements.append(Paragraph("Detection Summary", styles['Heading2']))
        
        ts = detection_data.get("timestamp", datetime.datetime.utcnow().isoformat())
        data = [
            ["Media ID:", media_id],
            ["Date Detected:", ts],
            ["Platform:", detection_data.get("platform", "Unknown")],
            ["Risk Level:", detection_data.get("risk_level", "Unknown")],
            ["Estimated Views:", str(detection_data.get("views", 0))],
            ["Revenue Loss Estimate:", f"${detection_data.get('revenue_estimate', 0):.2f}"]
        ]
        
        t = Table(data, colWidths=[150, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # AI Explanation
        elements.append(Paragraph("AI Explainability Analysis", styles['Heading2']))
        explanation = detection_data.get("text_explanation", "No AI explanation available.")
        elements.append(Paragraph(explanation, styles['Normal']))
        elements.append(Spacer(1, 20))

        # Heatmap
        if heatmap_path and os.path.exists(heatmap_path):
            elements.append(Paragraph("Visual Evidence (Similarity Heatmap)", styles['Heading2']))
            elements.append(Spacer(1, 10))
            img = RLImage(heatmap_path, width=450, height=150)
            elements.append(img)
            elements.append(Spacer(1, 20))

        # Footer
        elements.append(Spacer(1, 30))
        footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)
        elements.append(Paragraph("This report is automatically generated by MediaShield AI's digital forensics engine and constitutes formal notification of copyright infringement.", footer_style))

        doc.build(elements)
        return out_path

    except Exception as e:
        print(f"Error generating PDF: {e}")
        return None
